// Categories seeder - Mock data cho categories
export let categories = [
  {
    id: 1,
    name: "Chăm sóc tóc",
    description: "Các dịch vụ chăm sóc và làm đẹp tóc",
    slug: "cham-soc-toc",
    icon: "https://example.com/icons/hair-care.svg",
    color: "#FF6B6B",
    displayOrder: 1,
    isActive: true,
    parentCategory: null,
    level: 0,
    path: "",
    serviceCount: 0,
    seoTitle: "Dịch vụ chăm sóc tóc chuyên nghiệp",
    seoDescription:
      "Các dịch vụ chăm sóc tóc đa dạng từ cắt, nhuộm, uốn đến tạo kiểu",
  },
  {
    id: 2,
    name: "Chăm sóc da",
    description: "Các dịch vụ chăm sóc và làm đẹp da mặt",
    slug: "cham-soc-da",
    icon: "https://example.com/icons/skin-care.svg",
    color: "#4ECDC4",
    displayOrder: 2,
    isActive: true,
    parentCategory: null,
    level: 0,
    path: "",
    serviceCount: 0,
    seoTitle: "Dịch vụ chăm sóc da mặt chuyên nghiệp",
    seoDescription: "Các dịch vụ chăm sóc da mặt từ cơ bản đến cao cấp",
  },
  {
    id: 3,
    name: "Massage & Thư giãn",
    description: "Các dịch vụ massage và thư giãn toàn thân",
    slug: "massage-thu-gian",
    icon: "https://example.com/icons/massage.svg",
    color: "#45B7D1",
    displayOrder: 3,
    isActive: true,
    parentCategory: null,
    level: 0,
    path: "",
    serviceCount: 0,
    seoTitle: "Dịch vụ massage và thư giãn",
    seoDescription: "Các dịch vụ massage từ cơ bản đến chuyên sâu",
  },
  {
    id: 4,
    name: "Chăm sóc móng",
    description: "Các dịch vụ chăm sóc và làm đẹp móng tay, móng chân",
    slug: "cham-soc-mong",
    icon: "https://example.com/icons/nail-care.svg",
    color: "#96CEB4",
    displayOrder: 4,
    isActive: true,
    parentCategory: null,
    level: 0,
    path: "",
    serviceCount: 0,
    seoTitle: "Dịch vụ chăm sóc móng chuyên nghiệp",
    seoDescription: "Các dịch vụ làm móng tay, móng chân đẹp và chuyên nghiệp",
  },
  {
    id: 5,
    name: "Spa & Wellness",
    description: "Các dịch vụ spa và wellness cao cấp",
    slug: "spa-wellness",
    icon: "https://example.com/icons/spa.svg",
    color: "#FECA57",
    displayOrder: 5,
    isActive: true,
    parentCategory: null,
    level: 0,
    path: "",
    serviceCount: 0,
    seoTitle: "Dịch vụ spa và wellness cao cấp",
    seoDescription: "Các gói dịch vụ spa và wellness toàn diện",
  },
  // Subcategories for "Chăm sóc tóc"
  {
    id: 6,
    name: "Cắt tóc",
    description: "Dịch vụ cắt tóc nam và nữ",
    slug: "cat-toc",
    icon: "https://example.com/icons/haircut.svg",
    color: "#FF6B6B",
    displayOrder: 1,
    isActive: true,
    parentCategory: 1,
    level: 1,
    path: "Chăm sóc tóc",
    serviceCount: 0,
    seoTitle: "Dịch vụ cắt tóc chuyên nghiệp",
    seoDescription: "Cắt tóc nam và nữ theo phong cách hiện đại",
  },
  {
    id: 7,
    name: "Nhuộm tóc",
    description: "Dịch vụ nhuộm tóc với nhiều màu sắc",
    slug: "nhuom-toc",
    icon: "https://example.com/icons/hair-color.svg",
    color: "#FF6B6B",
    displayOrder: 2,
    isActive: true,
    parentCategory: 1,
    level: 1,
    path: "Chăm sóc tóc",
    serviceCount: 0,
    seoTitle: "Dịch vụ nhuộm tóc đa dạng",
    seoDescription: "Nhuộm tóc với nhiều màu sắc và kỹ thuật hiện đại",
  },
  {
    id: 8,
    name: "Uốn tóc",
    description: "Dịch vụ uốn tóc tạo kiểu",
    slug: "uon-toc",
    icon: "https://example.com/icons/hair-perm.svg",
    color: "#FF6B6B",
    displayOrder: 3,
    isActive: true,
    parentCategory: 1,
    level: 1,
    path: "Chăm sóc tóc",
    serviceCount: 0,
    seoTitle: "Dịch vụ uốn tóc chuyên nghiệp",
    seoDescription: "Uốn tóc tạo kiểu với các kỹ thuật hiện đại",
  },
  // Subcategories for "Chăm sóc da"
  {
    id: 9,
    name: "Facial cơ bản",
    description: "Các dịch vụ facial chăm sóc da cơ bản",
    slug: "facial-co-ban",
    icon: "https://example.com/icons/facial-basic.svg",
    color: "#4ECDC4",
    displayOrder: 1,
    isActive: true,
    parentCategory: 2,
    level: 1,
    path: "Chăm sóc da",
    serviceCount: 0,
    seoTitle: "Dịch vụ facial cơ bản",
    seoDescription: "Các dịch vụ facial chăm sóc da cơ bản",
  },
  {
    id: 10,
    name: "Facial cao cấp",
    description: "Các dịch vụ facial chăm sóc da cao cấp",
    slug: "facial-cao-cap",
    icon: "https://example.com/icons/facial-premium.svg",
    color: "#4ECDC4",
    displayOrder: 2,
    isActive: true,
    parentCategory: 2,
    level: 1,
    path: "Chăm sóc da",
    serviceCount: 0,
    seoTitle: "Dịch vụ facial cao cấp",
    seoDescription:
      "Các dịch vụ facial chăm sóc da cao cấp với công nghệ hiện đại",
  },
  {
    id: 11,
    name: "Trị mụn",
    description: "Các dịch vụ trị mụn chuyên nghiệp",
    slug: "tri-mun",
    icon: "https://example.com/icons/acne-treatment.svg",
    color: "#4ECDC4",
    displayOrder: 3,
    isActive: true,
    parentCategory: 2,
    level: 1,
    path: "Chăm sóc da",
    serviceCount: 0,
    seoTitle: "Dịch vụ trị mụn chuyên nghiệp",
    seoDescription: "Các dịch vụ trị mụn an toàn và hiệu quả",
  },
  // Subcategories for "Massage & Thư giãn"
  {
    id: 12,
    name: "Massage toàn thân",
    description: "Dịch vụ massage toàn thân thư giãn",
    slug: "massage-toan-than",
    icon: "https://example.com/icons/body-massage.svg",
    color: "#45B7D1",
    displayOrder: 1,
    isActive: true,
    parentCategory: 3,
    level: 1,
    path: "Massage & Thư giãn",
    serviceCount: 0,
    seoTitle: "Dịch vụ massage toàn thân",
    seoDescription: "Massage toàn thân giúp thư giãn và giảm stress",
  },
  {
    id: 13,
    name: "Massage chân",
    description: "Dịch vụ massage chân chuyên nghiệp",
    slug: "massage-chan",
    icon: "https://example.com/icons/foot-massage.svg",
    color: "#45B7D1",
    displayOrder: 2,
    isActive: true,
    parentCategory: 3,
    level: 1,
    path: "Massage & Thư giãn",
    serviceCount: 0,
    seoTitle: "Dịch vụ massage chân",
    seoDescription: "Massage chân giúp lưu thông máu và thư giãn",
  },
  {
    id: 14,
    name: "Massage đá nóng",
    description: "Dịch vụ massage với đá nóng",
    slug: "massage-da-nong",
    icon: "https://example.com/icons/hot-stone-massage.svg",
    color: "#45B7D1",
    displayOrder: 3,
    isActive: true,
    parentCategory: 3,
    level: 1,
    path: "Massage & Thư giãn",
    serviceCount: 0,
    seoTitle: "Dịch vụ massage đá nóng",
    seoDescription: "Massage đá nóng giúp thư giãn sâu và giảm đau nhức",
  },
  // Subcategories for "Chăm sóc móng"
  {
    id: 15,
    name: "Manicure",
    description: "Dịch vụ chăm sóc móng tay",
    slug: "manicure",
    icon: "https://example.com/icons/manicure.svg",
    color: "#96CEB4",
    displayOrder: 1,
    isActive: true,
    parentCategory: 4,
    level: 1,
    path: "Chăm sóc móng",
    serviceCount: 0,
    seoTitle: "Dịch vụ manicure chuyên nghiệp",
    seoDescription: "Chăm sóc và làm đẹp móng tay chuyên nghiệp",
  },
  {
    id: 16,
    name: "Pedicure",
    description: "Dịch vụ chăm sóc móng chân",
    slug: "pedicure",
    icon: "https://example.com/icons/pedicure.svg",
    color: "#96CEB4",
    displayOrder: 2,
    isActive: true,
    parentCategory: 4,
    level: 1,
    path: "Chăm sóc móng",
    serviceCount: 0,
    seoTitle: "Dịch vụ pedicure chuyên nghiệp",
    seoDescription: "Chăm sóc và làm đẹp móng chân chuyên nghiệp",
  },
  {
    id: 17,
    name: "Nail Art",
    description: "Dịch vụ vẽ nail art",
    slug: "nail-art",
    icon: "https://example.com/icons/nail-art.svg",
    color: "#96CEB4",
    displayOrder: 3,
    isActive: true,
    parentCategory: 4,
    level: 1,
    path: "Chăm sóc móng",
    serviceCount: 0,
    seoTitle: "Dịch vụ nail art sáng tạo",
    seoDescription: "Vẽ nail art với nhiều mẫu mã đa dạng và sáng tạo",
  },
  // Subcategories for "Spa & Wellness"
  {
    id: 18,
    name: "Gói spa cơ bản",
    description: "Các gói spa cơ bản cho người mới",
    slug: "goi-spa-co-ban",
    icon: "https://example.com/icons/spa-basic.svg",
    color: "#FECA57",
    displayOrder: 1,
    isActive: true,
    parentCategory: 5,
    level: 1,
    path: "Spa & Wellness",
    serviceCount: 0,
    seoTitle: "Gói spa cơ bản",
    seoDescription: "Các gói spa cơ bản phù hợp cho người mới bắt đầu",
  },
  {
    id: 19,
    name: "Gói spa cao cấp",
    description: "Các gói spa cao cấp với nhiều dịch vụ",
    slug: "goi-spa-cao-cap",
    icon: "https://example.com/icons/spa-premium.svg",
    color: "#FECA57",
    displayOrder: 2,
    isActive: true,
    parentCategory: 5,
    level: 1,
    path: "Spa & Wellness",
    serviceCount: 0,
    seoTitle: "Gói spa cao cấp",
    seoDescription: "Các gói spa cao cấp với nhiều dịch vụ chuyên sâu",
  },
  {
    id: 20,
    name: "Detox & Thải độc",
    description: "Các dịch vụ detox và thải độc cơ thể",
    slug: "detox-thai-doc",
    icon: "https://example.com/icons/detox.svg",
    color: "#FECA57",
    displayOrder: 3,
    isActive: true,
    parentCategory: 5,
    level: 1,
    path: "Spa & Wellness",
    serviceCount: 0,
    seoTitle: "Dịch vụ detox và thải độc",
    seoDescription: "Các dịch vụ detox và thải độc cơ thể an toàn và hiệu quả",
  },
];

// Helper functions
export const getCategories = () => categories;
export const setCategories = (newCategories) => {
  categories = newCategories;
};

export const getCategoryById = (id) => {
  return categories.find((cat) => cat.id === id);
};

export const getCategoriesByParent = (parentId) => {
  return categories.filter((cat) => cat.parentCategory === parentId);
};

export const getRootCategories = () => {
  return categories.filter((cat) => cat.parentCategory === null);
};

export const getCategoryTree = () => {
  const buildTree = (parentId = null) => {
    return categories
      .filter((cat) => cat.parentCategory === parentId)
      .map((cat) => ({
        ...cat,
        subcategories: buildTree(cat.id),
      }));
  };
  return buildTree();
};
