// Notifications seeder - Mock data cho notifications
export let templates = [
  {
    id: 1,
    name: "Xác nhận đặt lịch",
    type: "confirmation",
    trigger: "appointment_created",
    subject: "Xác nhận đặt lịch thành công",
    content:
      "Xin chào {{customer_name}},\n\nChúng tôi xác nhận lịch hẹn của bạn:\n- Dịch vụ: {{service_name}}\n- Thời gian: {{start_time}} ngày {{appointment_date}}\n- Địa chỉ: {{branch_address}}\n\nVui lòng đến đúng giờ. Cảm ơn bạn!",
    channels: ["sms", "email"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: 2,
    name: "Nhắc lịch hẹn",
    type: "reminder",
    trigger: "appointment_reminder",
    subject: "Nhắc nhở lịch hẹn",
    content:
      "Xin chào {{customer_name}},\n\nNhắc nhở: Bạn có lịch hẹn {{service_name}} vào {{start_time}} ngày {{appointment_date}}.\n\nVui lòng đến đúng giờ. Cảm ơn bạn!",
    channels: ["sms"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: 3,
    name: "Thay đổi lịch hẹn",
    type: "reschedule",
    trigger: "appointment_rescheduled",
    subject: "Thông báo thay đổi lịch hẹn",
    content:
      "Xin chào {{customer_name}},\n\nLịch hẹn của bạn đã được thay đổi:\n- Dịch vụ: {{service_name}}\n- Thời gian mới: {{start_time}} ngày {{appointment_date}}\n\nVui lòng xác nhận. Cảm ơn bạn!",
    channels: ["sms", "email"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: 4,
    name: "Cảm ơn sau dịch vụ",
    type: "thank_you",
    trigger: "appointment_completed",
    subject: "Cảm ơn bạn đã sử dụng dịch vụ",
    content:
      "Xin chào {{customer_name}},\n\nCảm ơn bạn đã sử dụng dịch vụ {{service_name}}.\n\nChúng tôi hy vọng bạn hài lòng với dịch vụ. Hẹn gặp lại bạn lần sau!",
    channels: ["email"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: 5,
    name: "Hủy lịch hẹn",
    type: "cancellation",
    trigger: "appointment_cancelled",
    subject: "Thông báo hủy lịch hẹn",
    content:
      "Xin chào {{customer_name}},\n\nLịch hẹn {{service_name}} của bạn đã được hủy.\n\nChúng tôi rất tiếc vì sự bất tiện này. Vui lòng liên hệ để đặt lịch mới.",
    channels: ["sms", "email"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: 6,
    name: "Khuyến mãi đặc biệt",
    type: "promotion",
    trigger: "promotion_created",
    subject: "Khuyến mãi đặc biệt dành cho bạn",
    content:
      "Xin chào {{customer_name}},\n\nChúng tôi có khuyến mãi đặc biệt dành cho bạn:\n- Giảm 20% cho dịch vụ {{service_name}}\n- Áp dụng đến hết tháng\n\nĐặt lịch ngay để không bỏ lỡ!",
    channels: ["email"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: 7,
    name: "Nhắc nhở thanh toán",
    type: "other",
    trigger: "manual",
    subject: "Nhắc nhở thanh toán",
    content:
      "Xin chào {{customer_name}},\n\nBạn có hóa đơn chưa thanh toán cho dịch vụ {{service_name}}.\n- Số tiền: {{amount}}\n- Hạn thanh toán: {{due_date}}\n\nVui lòng thanh toán sớm. Cảm ơn!",
    channels: ["sms", "email"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: 8,
    name: "Chúc mừng sinh nhật",
    type: "birthday",
    trigger: "customer_birthday",
    subject: "Chúc mừng sinh nhật!",
    content:
      "Xin chào {{customer_name}},\n\nChúc mừng sinh nhật! Chúng tôi dành tặng bạn ưu đãi đặc biệt:\n- Giảm 30% cho tất cả dịch vụ\n- Tặng kèm dịch vụ chăm sóc da\n\nHẹn gặp bạn tại spa!",
    channels: ["email"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: 9,
    name: "Đánh giá dịch vụ",
    type: "feedback",
    trigger: "feedback_request",
    subject: "Đánh giá dịch vụ của bạn",
    content:
      "Xin chào {{customer_name}},\n\nCảm ơn bạn đã sử dụng dịch vụ {{service_name}}.\n\nChúng tôi rất mong nhận được đánh giá của bạn để cải thiện chất lượng dịch vụ.\n\nVui lòng đánh giá tại: {{feedback_link}",
    channels: ["email"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: 10,
    name: "Thông báo bảo trì",
    type: "other",
    trigger: "manual",
    subject: "Thông báo bảo trì hệ thống",
    content:
      "Xin chào {{customer_name}},\n\nChúng tôi sẽ bảo trì hệ thống từ {{start_time}} đến {{end_time}} ngày {{date}}.\n\nTrong thời gian này, một số dịch vụ có thể bị gián đoạn.\n\nXin lỗi vì sự bất tiện này!",
    channels: ["email"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: 11,
    name: "Chào mừng khách hàng mới",
    type: "other",
    trigger: "manual",
    subject: "Chào mừng bạn đến với spa!",
    content:
      "Xin chào {{customer_name}},\n\nChào mừng bạn đến với spa của chúng tôi!\n\nChúng tôi dành tặng bạn ưu đãi đặc biệt:\n- Giảm 50% cho lần đầu sử dụng\n- Tư vấn miễn phí\n\nHẹn gặp bạn tại spa!",
    channels: ["email"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: 12,
    name: "Nhắc nhở lịch hẹn 24h",
    type: "reminder",
    trigger: "appointment_reminder",
    subject: "Nhắc nhở lịch hẹn ngày mai",
    content:
      "Xin chào {{customer_name}},\n\nNhắc nhở: Bạn có lịch hẹn {{service_name}} vào {{start_time}} ngày mai ({{appointment_date}}).\n\nVui lòng đến đúng giờ. Cảm ơn bạn!",
    channels: ["sms"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: 13,
    name: "Thông báo khuyến mãi mùa",
    type: "promotion",
    trigger: "promotion_created",
    subject: "Khuyến mãi mùa hè",
    content:
      "Xin chào {{customer_name}},\n\nMùa hè đến rồi! Chúng tôi có khuyến mãi đặc biệt:\n- Gói chăm sóc da mùa hè\n- Giảm 25% cho tất cả dịch vụ\n- Tặng kèm kem chống nắng\n\nĐặt lịch ngay!",
    channels: ["email"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: 14,
    name: "Nhắc nhở lịch hẹn 2h",
    type: "reminder",
    trigger: "appointment_reminder",
    subject: "Nhắc nhở lịch hẹn sắp tới",
    content:
      "Xin chào {{customer_name}},\n\nNhắc nhở: Bạn có lịch hẹn {{service_name}} vào {{start_time}} hôm nay.\n\nVui lòng chuẩn bị và đến đúng giờ. Cảm ơn bạn!",
    channels: ["sms"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: 15,
    name: "Thông báo dịch vụ mới",
    type: "other",
    trigger: "manual",
    subject: "Dịch vụ mới tại spa",
    content:
      "Xin chào {{customer_name}},\n\nChúng tôi vừa ra mắt dịch vụ mới: {{service_name}}\n- Công nghệ tiên tiến\n- Giá ưu đãi đặc biệt\n- Đặt lịch ngay để trải nghiệm!\n\nHẹn gặp bạn tại spa!",
    channels: ["email"],
    createdBy: "68c6fd963411a8af5b3c90d2",
    isActive: true,
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
];

export let notificationLogs = [
  {
    id: 1,
    templateId: 1,
    templateName: "Xác nhận đặt lịch",
    customerName: "Nguyễn Thị A",
    customerPhone: "0901234567",
    customerEmail: "nguyenthi.a@email.com",
    channel: "sms",
    status: "sent",
    content:
      "Xin chào Nguyễn Thị A,\n\nChúng tôi xác nhận lịch hẹn của bạn:\n- Dịch vụ: Massage thư giãn\n- Thời gian: 10:00 ngày 20/01/2024\n- Địa chỉ: 123 Đường ABC, Quận 1, TP.HCM\n\nVui lòng đến đúng giờ. Cảm ơn bạn!",
    sentAt: "2024-01-15T10:05:00Z",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: 2,
    templateId: 2,
    templateName: "Nhắc lịch hẹn",
    customerName: "Trần Văn B",
    customerPhone: "0912345678",
    customerEmail: "tranvan.b@email.com",
    channel: "sms",
    status: "sent",
    content:
      "Xin chào Trần Văn B,\n\nNhắc nhở: Bạn có lịch hẹn Facial chăm sóc da vào 14:30 ngày 21/01/2024.\n\nVui lòng đến đúng giờ. Cảm ơn bạn!",
    sentAt: "2024-01-12T14:25:00Z",
    createdAt: "2024-01-12T14:20:00Z",
  },
  {
    id: 3,
    templateId: 1,
    templateName: "Xác nhận đặt lịch",
    customerName: "Lê Thị C",
    customerPhone: "0923456789",
    customerEmail: "lethi.c@email.com",
    channel: "email",
    status: "failed",
    content:
      "Xin chào Lê Thị C,\n\nChúng tôi xác nhận lịch hẹn của bạn:\n- Dịch vụ: Cắt tóc & tạo kiểu\n- Thời gian: 16:00 ngày 18/01/2024\n- Địa chỉ: 123 Đường ABC, Quận 1, TP.HCM\n\nVui lòng đến đúng giờ. Cảm ơn bạn!",
    sentAt: null,
    createdAt: "2024-01-10T16:00:00Z",
  },
  {
    id: 4,
    templateId: 4,
    templateName: "Cảm ơn sau dịch vụ",
    customerName: "Phạm Văn D",
    customerPhone: "0934567890",
    customerEmail: "phamvan.d@email.com",
    channel: "email",
    status: "sent",
    content:
      "Xin chào Phạm Văn D,\n\nCảm ơn bạn đã sử dụng dịch vụ Nhuộm tóc cao cấp.\n\nChúng tôi hy vọng bạn hài lòng với dịch vụ. Hẹn gặp lại bạn lần sau!",
    sentAt: "2024-01-22T11:05:00Z",
    createdAt: "2024-01-22T11:00:00Z",
  },
  {
    id: 5,
    templateId: 2,
    templateName: "Nhắc lịch hẹn",
    customerName: "Hoàng Thị E",
    customerPhone: "0945678901",
    customerEmail: "hoangthi.e@email.com",
    channel: "sms",
    status: "sent",
    content:
      "Xin chào Hoàng Thị E,\n\nNhắc nhở: Bạn có lịch hẹn Facial cao cấp vào 13:00 ngày 23/01/2024.\n\nVui lòng đến đúng giờ. Cảm ơn bạn!",
    sentAt: "2024-01-23T12:55:00Z",
    createdAt: "2024-01-23T12:50:00Z",
  },
  {
    id: 6,
    templateId: 4,
    templateName: "Cảm ơn sau dịch vụ",
    customerName: "Vũ Văn F",
    customerPhone: "0956789012",
    customerEmail: "vuvan.f@email.com",
    channel: "email",
    status: "sent",
    content:
      "Xin chào Vũ Văn F,\n\nCảm ơn bạn đã sử dụng dịch vụ Massage chân thư giãn.\n\nChúng tôi hy vọng bạn hài lòng với dịch vụ. Hẹn gặp lại bạn lần sau!",
    sentAt: "2024-01-24T16:20:00Z",
    createdAt: "2024-01-24T16:15:00Z",
  },
  {
    id: 7,
    templateId: 1,
    templateName: "Xác nhận đặt lịch",
    customerName: "Đặng Thị G",
    customerPhone: "0967890123",
    customerEmail: "dangthi.g@email.com",
    channel: "email",
    status: "sent",
    content:
      "Xin chào Đặng Thị G,\n\nChúng tôi xác nhận lịch hẹn của bạn:\n- Dịch vụ: Gói spa cơ bản\n- Thời gian: 10:00 ngày 25/01/2024\n- Địa chỉ: 123 Đường ABC, Quận 1, TP.HCM\n\nVui lòng đến đúng giờ. Cảm ơn bạn!",
    sentAt: "2024-01-21T10:05:00Z",
    createdAt: "2024-01-21T10:00:00Z",
  },
  {
    id: 8,
    templateId: 2,
    templateName: "Nhắc lịch hẹn",
    customerName: "Bùi Văn H",
    customerPhone: "0978901234",
    customerEmail: "buivan.h@email.com",
    channel: "sms",
    status: "sent",
    content:
      "Xin chào Bùi Văn H,\n\nNhắc nhở: Bạn có lịch hẹn Cắt tóc & tạo kiểu vào 11:00 ngày 26/01/2024.\n\nVui lòng đến đúng giờ. Cảm ơn bạn!",
    sentAt: "2024-01-26T10:55:00Z",
    createdAt: "2024-01-26T10:50:00Z",
  },
  {
    id: 9,
    templateId: 4,
    templateName: "Cảm ơn sau dịch vụ",
    customerName: "Ngô Thị I",
    customerPhone: "0989012345",
    customerEmail: "ngothi.i@email.com",
    channel: "email",
    status: "sent",
    content:
      "Xin chào Ngô Thị I,\n\nCảm ơn bạn đã sử dụng dịch vụ Manicure cơ bản.\n\nChúng tôi hy vọng bạn hài lòng với dịch vụ. Hẹn gặp lại bạn lần sau!",
    sentAt: "2024-01-27T15:05:00Z",
    createdAt: "2024-01-27T15:00:00Z",
  },
  {
    id: 10,
    templateId: 1,
    templateName: "Xác nhận đặt lịch",
    customerName: "Lý Văn J",
    customerPhone: "0990123456",
    customerEmail: "lyvan.j@email.com",
    channel: "sms",
    status: "sent",
    content:
      "Xin chào Lý Văn J,\n\nChúng tôi xác nhận lịch hẹn của bạn:\n- Dịch vụ: Massage thư giãn\n- Thời gian: 16:00 ngày 28/01/2024\n- Địa chỉ: 123 Đường ABC, Quận 1, TP.HCM\n\nVui lòng đến đúng giờ. Cảm ơn bạn!",
    sentAt: "2024-01-24T16:05:00Z",
    createdAt: "2024-01-24T16:00:00Z",
  },
  {
    id: 11,
    templateId: 2,
    templateName: "Nhắc lịch hẹn",
    customerName: "Trịnh Thị K",
    customerPhone: "0901234568",
    customerEmail: "trinhthi.k@email.com",
    channel: "sms",
    status: "sent",
    content:
      "Xin chào Trịnh Thị K,\n\nNhắc nhở: Bạn có lịch hẹn Nail art sáng tạo vào 10:30 ngày 29/01/2024.\n\nVui lòng đến đúng giờ. Cảm ơn bạn!",
    sentAt: "2024-01-29T10:25:00Z",
    createdAt: "2024-01-29T10:20:00Z",
  },
  {
    id: 12,
    templateId: 4,
    templateName: "Cảm ơn sau dịch vụ",
    customerName: "Đinh Văn L",
    customerPhone: "0912345679",
    customerEmail: "dinhvan.l@email.com",
    channel: "email",
    status: "sent",
    content:
      "Xin chào Đinh Văn L,\n\nCảm ơn bạn đã sử dụng dịch vụ Massage đá nóng.\n\nChúng tôi hy vọng bạn hài lòng với dịch vụ. Hẹn gặp lại bạn lần sau!",
    sentAt: "2024-01-30T16:35:00Z",
    createdAt: "2024-01-30T16:30:00Z",
  },
  {
    id: 13,
    templateId: 1,
    templateName: "Xác nhận đặt lịch",
    customerName: "Phan Thị M",
    customerPhone: "0923456790",
    customerEmail: "phanthi.m@email.com",
    channel: "email",
    status: "sent",
    content:
      "Xin chào Phan Thị M,\n\nChúng tôi xác nhận lịch hẹn của bạn:\n- Dịch vụ: Gói spa cao cấp\n- Thời gian: 09:00 ngày 31/01/2024\n- Địa chỉ: 123 Đường ABC, Quận 1, TP.HCM\n\nVui lòng đến đúng giờ. Cảm ơn bạn!",
    sentAt: "2024-01-27T09:05:00Z",
    createdAt: "2024-01-27T09:00:00Z",
  },
  {
    id: 14,
    templateId: 2,
    templateName: "Nhắc lịch hẹn",
    customerName: "Võ Văn N",
    customerPhone: "0934567901",
    customerEmail: "vovan.n@email.com",
    channel: "sms",
    status: "sent",
    content:
      "Xin chào Võ Văn N,\n\nNhắc nhở: Bạn có lịch hẹn Trị mụn chuyên sâu vào 14:00 ngày 01/02/2024.\n\nVui lòng đến đúng giờ. Cảm ơn bạn!",
    sentAt: "2024-02-01T13:55:00Z",
    createdAt: "2024-02-01T13:50:00Z",
  },
  {
    id: 15,
    templateId: 1,
    templateName: "Xác nhận đặt lịch",
    customerName: "Tôn Thị O",
    customerPhone: "0945679012",
    customerEmail: "tonthi.o@email.com",
    channel: "sms",
    status: "sent",
    content:
      "Xin chào Tôn Thị O,\n\nChúng tôi xác nhận lịch hẹn của bạn:\n- Dịch vụ: Cắt tóc & tạo kiểu\n- Thời gian: 11:30 ngày 02/02/2024\n- Địa chỉ: 123 Đường ABC, Quận 1, TP.HCM\n\nVui lòng đến đúng giờ. Cảm ơn bạn!",
    sentAt: "2024-01-29T11:35:00Z",
    createdAt: "2024-01-29T11:30:00Z",
  },
];

export const getTemplates = () => templates;
export const setTemplates = (newTemplates) => {
  templates = newTemplates;
};

export const getNotificationLogs = () => notificationLogs;
export const setNotificationLogs = (newLogs) => {
  notificationLogs = newLogs;
};
