export const tableDescriptions = {
  user: {
    description:
      "Bảng lưu trữ thông tin người dùng và khách hàng của hệ thống. Bao gồm thông tin xác thực (email, password), thông tin cá nhân, và dữ liệu khách hàng như tổng chi tiêu, cấp độ thành viên (Thường, Loyal, Premium, VIP), điểm tích lũy. Hỗ trợ quản lý cả admin và user thông qua field role.",
    fields: [
      {
        name: "_id",
        dataType: "ObjectId",
        type: "PK",
        description: "Khóa chính, định danh duy nhất cho mỗi user trong hệ thống",
        required: true,
      },
      {
        name: "name",
        dataType: "String",
        type: "field",
        description: "Họ và tên của người dùng, từ 2-50 ký tự",
        required: true,
      },
      {
        name: "email",
        dataType: "String",
        type: "UK",
        description: "Email đăng nhập, phải là email hợp lệ và duy nhất trong hệ thống",
        required: true,
      },
      {
        name: "phone",
        dataType: "String",
        type: "field",
        description: "Số điện thoại, từ 9-11 chữ số, không bắt buộc",
        required: false,
      },
      {
        name: "password",
        dataType: "String",
        type: "field",
        description: "Mật khẩu đã được mã hóa bằng bcrypt với 12 salt rounds, tối thiểu 6 ký tự",
        required: true,
      },
      {
        name: "avatar",
        dataType: "String",
        type: "field",
        description: "URL hình ảnh đại diện của người dùng",
        required: false,
      },
      {
        name: "role",
        dataType: "String",
        type: "field",
        description: "Vai trò trong hệ thống: 'user' (khách hàng) hoặc 'admin' (quản trị viên)",
        required: false,
      },
      {
        name: "isEmailVerified",
        dataType: "Boolean",
        type: "field",
        description: "Trạng thái xác thực email, mặc định false",
        required: false,
      },
      {
        name: "totalSpent",
        dataType: "Number",
        type: "field",
        description: "Tổng số tiền khách hàng đã chi tiêu, dùng để tính cấp độ thành viên",
        required: false,
      },
      {
        name: "level",
        dataType: "String",
        type: "field",
        description:
          "Cấp độ thành viên: 'Thường' (<2M), 'Loyal' (≥2M), 'Premium' (≥5M), 'VIP' (≥10M). Tự động cập nhật dựa trên totalSpent",
        required: false,
      },
      {
        name: "points",
        dataType: "Number",
        type: "field",
        description: "Điểm tích lũy của khách hàng, có thể dùng để đổi quà hoặc giảm giá",
        required: false,
      },
      {
        name: "preferences",
        dataType: "Object",
        type: "field",
        description:
          "Sở thích của khách hàng: dịch vụ yêu thích, nhân viên ưa thích, khung giờ booking, và phương thức liên lạc (SMS, email, phone)",
        required: false,
      },
      {
        name: "address",
        dataType: "Object",
        type: "field",
        description: "Địa chỉ của khách hàng bao gồm: street, city, state, zipCode",
        required: false,
      },
      {
        name: "createdAt",
        dataType: "Date",
        type: "field",
        description: "Thời điểm tạo tài khoản, tự động tạo bởi Mongoose timestamps",
        required: false,
      },
      {
        name: "updatedAt",
        dataType: "Date",
        type: "field",
        description: "Thời điểm cập nhật lần cuối, tự động cập nhật bởi Mongoose timestamps",
        required: false,
      },
    ],
    relationships: [
      {
        type: "one-to-many",
        target: "appointment",
        field: "customerId",
        description: "Một user có thể có nhiều appointment (lịch hẹn)",
      },
      {
        type: "one-to-one",
        target: "staff",
        field: "userId",
        description: "Một user có thể liên kết với một staff (nếu là nhân viên)",
      },
      {
        type: "one-to-many",
        target: "notification_log",
        field: "userId",
        description: "Một user có thể nhận nhiều thông báo",
      },
    ],
  },

  staff: {
    description:
      "Bảng lưu trữ thông tin nhân viên của spa. Bao gồm thông tin cá nhân, lịch làm việc theo từng ngày trong tuần, kỹ năng chuyên môn, và thông tin tài chính như tỷ lệ chia doanh thu, lương theo giờ, hoa hồng. Có thể liên kết với tài khoản User hoặc tạo độc lập.",
    fields: [
      {
        name: "_id",
        dataType: "ObjectId",
        type: "PK",
        description: "Khóa chính, định danh duy nhất cho mỗi nhân viên",
        required: true,
      },
      {
        name: "userId",
        dataType: "ObjectId",
        type: "FK",
        description: "Tham chiếu đến User nếu nhân viên có tài khoản trong hệ thống",
        required: false,
      },
      {
        name: "employeeId",
        dataType: "String",
        type: "UK",
        description: "Mã nhân viên duy nhất, tự động tạo dạng ST + timestamp + random",
        required: false,
      },
      {
        name: "name",
        dataType: "String",
        type: "field",
        description: "Tên nhân viên, tối đa 50 ký tự",
        required: true,
      },
      {
        name: "phone",
        dataType: "String",
        type: "field",
        description: "Số điện thoại nhân viên, 10-11 chữ số",
        required: false,
      },
      {
        name: "email",
        dataType: "String",
        type: "field",
        description: "Email nhân viên",
        required: false,
      },
      {
        name: "role",
        dataType: "String",
        type: "field",
        description:
          "Chức danh: Massage Therapist, Beauty Specialist, Hair Stylist, Nail Technician, Spa Therapist, Receptionist, Manager, hoặc Nhân viên",
        required: false,
      },
      {
        name: "skills",
        dataType: "Array",
        type: "field",
        description: "Danh sách kỹ năng chuyên môn của nhân viên",
        required: false,
      },
      {
        name: "workSchedule",
        dataType: "Object",
        type: "field",
        description:
          "Lịch làm việc theo từng ngày trong tuần (Monday-Sunday), mỗi ngày có start time, end time, và isWorking",
        required: false,
      },
      {
        name: "revenueShare",
        dataType: "Number",
        type: "field",
        description: "Tỷ lệ chia doanh thu (0-1), mặc định 0.3 (30%)",
        required: false,
      },
      {
        name: "isActive",
        dataType: "Boolean",
        type: "field",
        description: "Trạng thái hoạt động của nhân viên, true nếu đang làm việc",
        required: false,
      },
      {
        name: "hireDate",
        dataType: "Date",
        type: "field",
        description: "Ngày bắt đầu làm việc",
        required: false,
      },
      {
        name: "createdAt",
        dataType: "Date",
        type: "field",
        description: "Thời điểm tạo hồ sơ nhân viên",
        required: false,
      },
    ],
    relationships: [
      {
        type: "many-to-one",
        target: "user",
        field: "userId",
        description: "Một staff có thể liên kết với một user (tùy chọn)",
      },
      {
        type: "one-to-many",
        target: "appointment",
        field: "staffId",
        description: "Một staff có thể phục vụ nhiều appointment",
      },
    ],
  },

  category: {
    description:
      "Bảng lưu trữ danh mục dịch vụ của spa. Hỗ trợ cấu trúc phân cấp (parent-child) để tổ chức danh mục theo cây, ví dụ: 'Massage' > 'Thái Massage' > 'Thái Massage Chân'. Có thể sắp xếp thứ tự hiển thị và quản lý SEO.",
    fields: [
      {
        name: "_id",
        dataType: "ObjectId",
        type: "PK",
        description: "Khóa chính, định danh duy nhất cho mỗi danh mục",
        required: true,
      },
      {
        name: "name",
        dataType: "String",
        type: "field",
        description: "Tên danh mục, tối đa 100 ký tự",
        required: true,
      },
      {
        name: "description",
        dataType: "String",
        type: "field",
        description: "Mô tả chi tiết về danh mục, tối đa 500 ký tự",
        required: false,
      },
      {
        name: "slug",
        dataType: "String",
        type: "UK",
        description: "URL-friendly version của tên danh mục, tự động tạo từ name, dùng cho SEO",
        required: false,
      },
      {
        name: "icon",
        dataType: "String",
        type: "field",
        description: "URL icon đại diện cho danh mục",
        required: false,
      },
      {
        name: "color",
        dataType: "String",
        type: "field",
        description: "Màu sắc hex (#RRGGBB) để hiển thị danh mục, mặc định #3B82F6",
        required: false,
      },
      {
        name: "displayOrder",
        dataType: "Number",
        type: "field",
        description: "Thứ tự hiển thị danh mục, số nhỏ hơn hiển thị trước",
        required: false,
      },
      {
        name: "isActive",
        dataType: "Boolean",
        type: "field",
        description: "Trạng thái hoạt động của danh mục",
        required: false,
      },
      {
        name: "parentCategory",
        dataType: "ObjectId",
        type: "FK",
        description: "Tham chiếu đến danh mục cha để tạo cấu trúc phân cấp",
        required: false,
      },
      {
        name: "level",
        dataType: "Number",
        type: "field",
        description: "Cấp độ trong cây danh mục (0 = root, 1 = con, 2 = cháu, ...)",
        required: false,
      },
      {
        name: "serviceCount",
        dataType: "Number",
        type: "field",
        description: "Số lượng dịch vụ thuộc danh mục này, tự động cập nhật",
        required: false,
      },
      {
        name: "createdBy",
        dataType: "ObjectId",
        type: "FK",
        description: "User (admin) tạo danh mục này",
        required: true,
      },
      {
        name: "createdAt",
        dataType: "Date",
        type: "field",
        description: "Thời điểm tạo danh mục",
        required: false,
      },
    ],
    relationships: [
      {
        type: "self-reference",
        target: "category",
        field: "parentCategory",
        description: "Danh mục có thể có danh mục cha để tạo cấu trúc phân cấp",
      },
      {
        type: "one-to-many",
        target: "service",
        field: "category",
        description: "Một category có thể chứa nhiều service",
      },
      {
        type: "many-to-one",
        target: "user",
        field: "createdBy",
        description: "Category được tạo bởi một admin user",
      },
    ],
  },

  service: {
    description:
      "Bảng lưu trữ thông tin dịch vụ spa. Mỗi dịch vụ thuộc một category, có thời gian thực hiện, giá, mô tả, và có thể có add-ons (dịch vụ bổ sung) hoặc combo (gói dịch vụ giảm giá). Hỗ trợ quản lý hình ảnh, tags, và đánh dấu dịch vụ nổi bật.",
    fields: [
      {
        name: "_id",
        dataType: "ObjectId",
        type: "PK",
        description: "Khóa chính, định danh duy nhất cho mỗi dịch vụ",
        required: true,
      },
      {
        name: "name",
        dataType: "String",
        type: "field",
        description: "Tên dịch vụ, tối đa 100 ký tự",
        required: true,
      },
      {
        name: "category",
        dataType: "ObjectId",
        type: "FK",
        description: "Tham chiếu đến Category mà dịch vụ này thuộc về",
        required: true,
      },
      {
        name: "duration",
        dataType: "Number",
        type: "field",
        description: "Thời gian thực hiện dịch vụ (phút), từ 15 đến 480 phút",
        required: true,
      },
      {
        name: "price",
        dataType: "Number",
        type: "field",
        description: "Giá dịch vụ (VNĐ), không được âm",
        required: true,
      },
      {
        name: "description",
        dataType: "String",
        type: "field",
        description: "Mô tả chi tiết dịch vụ, tối đa 1000 ký tự",
        required: false,
      },
      {
        name: "addOns",
        dataType: "Array",
        type: "field",
        description: "Danh sách dịch vụ bổ sung có thể thêm vào, mỗi add-on có name và price",
        required: false,
      },
      {
        name: "combo",
        dataType: "Array",
        type: "field",
        description:
          "Danh sách gói combo dịch vụ, mỗi combo có name, price (giá combo), và originalPrice (giá gốc nếu mua lẻ)",
        required: false,
      },
      {
        name: "isActive",
        dataType: "Boolean",
        type: "field",
        description: "Trạng thái hoạt động của dịch vụ",
        required: false,
      },
      {
        name: "isFeatured",
        dataType: "Boolean",
        type: "field",
        description: "Đánh dấu dịch vụ nổi bật, hiển thị ở trang chủ",
        required: false,
      },
      {
        name: "images",
        dataType: "Array",
        type: "field",
        description: "Danh sách URL hình ảnh minh họa dịch vụ",
        required: false,
      },
      {
        name: "tags",
        dataType: "Array",
        type: "field",
        description: "Thẻ từ khóa để tìm kiếm và phân loại dịch vụ",
        required: false,
      },
      {
        name: "createdAt",
        dataType: "Date",
        type: "field",
        description: "Thời điểm tạo dịch vụ",
        required: false,
      },
    ],
    relationships: [
      {
        type: "many-to-one",
        target: "category",
        field: "category",
        description: "Service thuộc về một category",
      },
      {
        type: "one-to-many",
        target: "appointment",
        field: "serviceId",
        description: "Một service có thể được đặt trong nhiều appointment",
      },
    ],
  },

  appointment: {
    description:
      "Bảng lưu trữ thông tin lịch hẹn (booking) của khách hàng. Mỗi appointment liên kết một customer, một service, và một staff. Quản lý trạng thái lịch hẹn (pending, confirmed, in-progress, completed, cancelled, no-show), thanh toán, và hỗ trợ add-ons, combo, rating.",
    fields: [
      {
        name: "_id",
        dataType: "ObjectId",
        type: "PK",
        description: "Khóa chính, định danh duy nhất cho mỗi appointment",
        required: true,
      },
      {
        name: "appointmentNumber",
        dataType: "String",
        type: "UK",
        description:
          "Mã lịch hẹn duy nhất, tự động tạo dạng APT + YYMMDD + random 3 số (ví dụ: APT241215001)",
        required: true,
      },
      {
        name: "customerId",
        dataType: "ObjectId",
        type: "FK",
        description: "Tham chiếu đến User (khách hàng) đặt lịch",
        required: true,
      },
      {
        name: "serviceId",
        dataType: "ObjectId",
        type: "FK",
        description: "Tham chiếu đến Service được đặt",
        required: true,
      },
      {
        name: "staffId",
        dataType: "ObjectId",
        type: "FK",
        description: "Tham chiếu đến Staff phục vụ lịch hẹn này",
        required: true,
      },
      {
        name: "appointmentDate",
        dataType: "Date",
        type: "field",
        description: "Ngày diễn ra lịch hẹn",
        required: true,
      },
      {
        name: "startTime",
        dataType: "String",
        type: "field",
        description: "Giờ bắt đầu lịch hẹn (format HH:mm)",
        required: true,
      },
      {
        name: "endTime",
        dataType: "String",
        type: "field",
        description: "Giờ kết thúc lịch hẹn (format HH:mm)",
        required: true,
      },
      {
        name: "status",
        dataType: "String",
        type: "field",
        description:
          "Trạng thái: 'pending' (chờ xác nhận), 'confirmed' (đã xác nhận), 'in-progress' (đang thực hiện), 'completed' (hoàn thành), 'cancelled' (đã hủy), 'no-show' (không đến)",
        required: false,
      },
      {
        name: "totalAmount",
        dataType: "Number",
        type: "field",
        description: "Tổng số tiền của lịch hẹn (bao gồm service + add-ons)",
        required: true,
      },
      {
        name: "paymentStatus",
        dataType: "String",
        type: "field",
        description:
          "Trạng thái thanh toán: 'pending' (chưa thanh toán), 'paid' (đã thanh toán), 'partial' (thanh toán một phần), 'refunded' (đã hoàn tiền)",
        required: false,
      },
      {
        name: "paymentMethod",
        dataType: "String",
        type: "field",
        description:
          "Phương thức thanh toán: 'cash' (tiền mặt), 'card' (thẻ), 'bank_transfer' (chuyển khoản), 'points' (điểm), 'combo' (gói combo)",
        required: false,
      },
      {
        name: "notes",
        dataType: "String",
        type: "field",
        description: "Ghi chú về lịch hẹn, tối đa 500 ký tự",
        required: false,
      },
      {
        name: "addOns",
        dataType: "Array",
        type: "field",
        description:
          "Danh sách dịch vụ bổ sung đã thêm vào appointment này, mỗi item có serviceId, name, price, quantity",
        required: false,
      },
      {
        name: "rating",
        dataType: "Object",
        type: "field",
        description:
          "Đánh giá sau khi hoàn thành: score (1-5), comment, và ratedAt (thời điểm đánh giá)",
        required: false,
      },
      {
        name: "createdAt",
        dataType: "Date",
        type: "field",
        description: "Thời điểm tạo appointment",
        required: false,
      },
    ],
    relationships: [
      {
        type: "many-to-one",
        target: "user",
        field: "customerId",
        description: "Appointment thuộc về một customer (user)",
      },
      {
        type: "many-to-one",
        target: "service",
        field: "serviceId",
        description: "Appointment sử dụng một service",
      },
      {
        type: "many-to-one",
        target: "staff",
        field: "staffId",
        description: "Appointment được phục vụ bởi một staff",
      },
      {
        type: "one-to-many",
        target: "notification_log",
        field: "appointmentId",
        description: "Một appointment có thể có nhiều thông báo (reminder, confirmation, etc.)",
      },
    ],
  },

  notification_template: {
    description:
      "Bảng lưu trữ các mẫu thông báo (template) có thể tái sử dụng. Mỗi template có trigger (sự kiện kích hoạt), nội dung với biến động, kênh gửi (SMS, email, push, WhatsApp, phone), và điều kiện áp dụng. Hỗ trợ lên lịch gửi (immediate, scheduled, relative).",
    fields: [
      {
        name: "_id",
        dataType: "ObjectId",
        type: "PK",
        description: "Khóa chính, định danh duy nhất cho mỗi template",
        required: true,
      },
      {
        name: "name",
        dataType: "String",
        type: "field",
        description: "Tên mẫu thông báo, tối đa 100 ký tự",
        required: true,
      },
      {
        name: "type",
        dataType: "String",
        type: "field",
        description:
          "Loại thông báo: 'confirmation', 'reminder', 'reschedule', 'cancellation', 'thank_you', 'promotion', 'birthday', 'anniversary', 'feedback', 'other'",
        required: true,
      },
      {
        name: "trigger",
        dataType: "String",
        type: "field",
        description:
          "Sự kiện kích hoạt: 'appointment_created', 'appointment_reminder', 'appointment_rescheduled', 'appointment_cancelled', 'appointment_completed', 'customer_birthday', 'customer_anniversary', 'promotion_created', 'feedback_request', 'manual'",
        required: true,
      },
      {
        name: "subject",
        dataType: "String",
        type: "field",
        description: "Tiêu đề thông báo, tối đa 200 ký tự, hỗ trợ biến động {{variable}}",
        required: true,
      },
      {
        name: "content",
        dataType: "String",
        type: "field",
        description: "Nội dung thông báo, tối đa 2000 ký tự, hỗ trợ biến động {{variable}}",
        required: true,
      },
      {
        name: "channels",
        dataType: "Array",
        type: "field",
        description:
          "Danh sách kênh gửi: 'sms', 'email', 'push', 'whatsapp', 'phone'. Có thể gửi qua nhiều kênh cùng lúc",
        required: true,
      },
      {
        name: "variables",
        dataType: "Array",
        type: "field",
        description:
          "Danh sách biến động có thể dùng trong subject và content, mỗi biến có name, description, example",
        required: false,
      },
      {
        name: "timing",
        dataType: "Object",
        type: "field",
        description:
          "Thiết lập thời gian gửi: 'immediate' (gửi ngay), 'scheduled' (gửi vào giờ cụ thể), 'relative' (gửi sau X phút/giờ/ngày)",
        required: false,
      },
      {
        name: "conditions",
        dataType: "Object",
        type: "field",
        description:
          "Điều kiện áp dụng template: customerLevel, serviceTypes, branches, minAppointments, minSpent",
        required: false,
      },
      {
        name: "isActive",
        dataType: "Boolean",
        type: "field",
        description: "Trạng thái hoạt động của template",
        required: false,
      },
      {
        name: "priority",
        dataType: "Number",
        type: "field",
        description: "Độ ưu tiên gửi (1-10), số cao hơn = ưu tiên cao hơn",
        required: false,
      },
      {
        name: "createdBy",
        dataType: "ObjectId",
        type: "FK",
        description: "User (admin) tạo template này",
        required: true,
      },
      {
        name: "createdAt",
        dataType: "Date",
        type: "field",
        description: "Thời điểm tạo template",
        required: false,
      },
    ],
    relationships: [
      {
        type: "one-to-many",
        target: "notification_log",
        field: "templateId",
        description: "Một template có thể được sử dụng trong nhiều notification log",
      },
      {
        type: "many-to-one",
        target: "user",
        field: "createdBy",
        description: "Template được tạo bởi một admin user",
      },
    ],
  },

  notification_log: {
    description:
      "Bảng lưu trữ lịch sử gửi thông báo. Mỗi record là một lần gửi thông báo cụ thể, lưu thông tin người nhận, nội dung đã gửi, trạng thái (pending, sent, delivered, failed, bounced, opened, clicked), và metadata về provider, cost, retry. Hỗ trợ theo dõi hiệu quả gửi thông báo.",
    fields: [
      {
        name: "_id",
        dataType: "ObjectId",
        type: "PK",
        description: "Khóa chính, định danh duy nhất cho mỗi log",
        required: true,
      },
      {
        name: "templateId",
        dataType: "ObjectId",
        type: "FK",
        description: "Tham chiếu đến NotificationTemplate được sử dụng",
        required: true,
      },
      {
        name: "userId",
        dataType: "ObjectId",
        type: "FK",
        description: "Tham chiếu đến User nhận thông báo",
        required: true,
      },
      {
        name: "appointmentId",
        dataType: "ObjectId",
        type: "FK",
        description: "Tham chiếu đến Appointment liên quan (nếu có)",
        required: false,
      },
      {
        name: "channel",
        dataType: "String",
        type: "field",
        description:
          "Kênh gửi: 'sms', 'email', 'push', 'whatsapp', 'phone'. Mỗi log chỉ ghi một kênh (nếu gửi nhiều kênh sẽ có nhiều log)",
        required: true,
      },
      {
        name: "recipient",
        dataType: "Object",
        type: "field",
        description: "Thông tin người nhận: name, phone, email",
        required: false,
      },
      {
        name: "content",
        dataType: "Object",
        type: "field",
        description: "Nội dung đã gửi: subject (tiêu đề) và body (nội dung), đã được thay thế biến động",
        required: false,
      },
      {
        name: "status",
        dataType: "String",
        type: "field",
        description:
          "Trạng thái: 'pending' (chờ gửi), 'sent' (đã gửi), 'delivered' (đã giao), 'failed' (thất bại), 'bounced' (bị từ chối), 'opened' (đã mở - email), 'clicked' (đã click - email)",
        required: false,
      },
      {
        name: "sentAt",
        dataType: "Date",
        type: "field",
        description: "Thời điểm gửi thông báo",
        required: false,
      },
      {
        name: "deliveredAt",
        dataType: "Date",
        type: "field",
        description: "Thời điểm thông báo được giao",
        required: false,
      },
      {
        name: "retryCount",
        dataType: "Number",
        type: "field",
        description: "Số lần thử lại nếu gửi thất bại, mặc định 0",
        required: false,
      },
      {
        name: "cost",
        dataType: "Number",
        type: "field",
        description: "Chi phí gửi thông báo (nếu có, ví dụ SMS có phí)",
        required: false,
      },
      {
        name: "createdAt",
        dataType: "Date",
        type: "field",
        description: "Thời điểm tạo log",
        required: false,
      },
    ],
    relationships: [
      {
        type: "many-to-one",
        target: "notification_template",
        field: "templateId",
        description: "Notification log sử dụng một template",
      },
      {
        type: "many-to-one",
        target: "user",
        field: "userId",
        description: "Notification log gửi cho một user",
      },
      {
        type: "many-to-one",
        target: "appointment",
        field: "appointmentId",
        description: "Notification log có thể liên quan đến một appointment",
      },
    ],
  },

  contact: {
    description:
      "Bảng lưu trữ thông tin liên hệ và cài đặt của spa. Chỉ có một record duy nhất (hoặc một record active) chứa thông tin doanh nghiệp, địa chỉ, số điện thoại, email, mạng xã hội, giờ làm việc, logo, và thông tin SEO. Dùng để hiển thị trên website và các thông tin công khai.",
    fields: [
      {
        name: "_id",
        dataType: "ObjectId",
        type: "PK",
        description: "Khóa chính, định danh duy nhất",
        required: true,
      },
      {
        name: "businessName",
        dataType: "String",
        type: "field",
        description: "Tên doanh nghiệp spa, tối đa 100 ký tự",
        required: true,
      },
      {
        name: "businessDescription",
        dataType: "String",
        type: "field",
        description: "Mô tả về doanh nghiệp, tối đa 500 ký tự",
        required: false,
      },
      {
        name: "phone",
        dataType: "String",
        type: "field",
        description: "Số điện thoại liên hệ chính, 9-11 chữ số",
        required: true,
      },
      {
        name: "email",
        dataType: "String",
        type: "field",
        description: "Email liên hệ chính",
        required: true,
      },
      {
        name: "address",
        dataType: "Object",
        type: "field",
        description:
          "Địa chỉ đầy đủ: street (đường), city (thành phố), state (tỉnh/thành), zipCode (mã bưu điện), country (quốc gia, mặc định 'Việt Nam')",
        required: false,
      },
      {
        name: "socialMedia",
        dataType: "Object",
        type: "field",
        description:
          "Thông tin mạng xã hội: facebook, instagram, tiktok, youtube, zalo (URL)",
        required: false,
      },
      {
        name: "workingHours",
        dataType: "Object",
        type: "field",
        description:
          "Giờ làm việc theo từng ngày trong tuần (Monday-Sunday), mỗi ngày có isOpen, openTime, closeTime",
        required: false,
      },
      {
        name: "logo",
        dataType: "String",
        type: "field",
        description: "URL logo của spa",
        required: false,
      },
      {
        name: "isActive",
        dataType: "Boolean",
        type: "field",
        description: "Trạng thái active, chỉ có một record active tại một thời điểm",
        required: false,
      },
      {
        name: "seo",
        dataType: "Object",
        type: "field",
        description:
          "Thông tin SEO: title (tối đa 60 ký tự), description (tối đa 160 ký tự), keywords (mảng từ khóa)",
        required: false,
      },
      {
        name: "createdAt",
        dataType: "Date",
        type: "field",
        description: "Thời điểm tạo record",
        required: false,
      },
    ],
    relationships: [],
  },
};

